stages:
  - test
test_app:
  stage: test
  tags: 
    - dev
  script:
    - cd crawler-app
    - pip3 install -r requirements.txt -r requirements-test.txt
    - python3 -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py