stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo 'Building'

test_app:
  stage: test
  tags: 
    - dev
  script:
    - cd crawler-app
    - pip3 install -r requirements.txt -r requirements-test.txt
    - python3 -m unittest discover -s tests/ 
    - coverage run -m unittest discover -s tests/ 
    - coverage report --include crawler/crawler.py

test_ui:
  stage: test
  tags: 
    - dev
  script:
    - cd crawler-ui
    - pip install -r requirements.txt -r requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py

deploy_job:
  image: docker:stable
  services:
    - docker:dind
  stage: deploy
  tags: 
    - dev
  script:
    - echo 'Deploy app&ui'
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - cd crawler-ui
    - docker build -t inks/crawler-ui:1.0 .
    - docker push inks/crawler-ui:1.0
    