---
global:
  scrape_interval: '5s'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'crawler-ui'
    static_configs:
      - targets:
          - 'crawler-ui:8000'

  - job_name: 'crawler-app'
    static_configs:
      - targets:
          - 'crawler-app:8000'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080'

